#!/usr/bin/env python3
"""
Complete Odoo 19 setup and API key generation using Playwright.
Final version with all form fields handled.
"""

import time
import sys
import re
from playwright.sync_api import sync_playwright, TimeoutError as PlaywrightTimeoutError

# Configuration
ODOO_URL = "http://localhost:8069"
ADMIN_EMAIL = "admin@example.com"
ADMIN_PASSWORD = "Admin@123456"
DB_NAME = "odoo_production"
MASTER_PASSWORD = "zmiy-853z-yg9k"  # Auto-generated by Odoo
API_KEY_NAME = "AI Employee Integration"


def complete_setup():
    """Complete Odoo setup and generate API key."""

    with sync_playwright() as p:
        browser = p.chromium.launch(headless=False, slow_mo=200)
        context = browser.new_context()
        page = context.new_page()

        try:
            print("="*60)
            print("Odoo 19 Setup - Starting")
            print("="*60)

            # Navigate to database manager
            print(f"\n1. Opening database manager...")
            page.goto(f"{ODOO_URL}/web/database/manager", wait_until="networkidle", timeout=30000)
            time.sleep(2)

            # Click "Create Database" button
            print("2. Clicking 'Create Database' button...")
            page.click("button[data-bs-target='.o_database_create']")
            time.sleep(1)

            # Wait for modal to be visible
            page.wait_for_selector(".o_database_create", state="visible", timeout=5000)

            # Fill master password
            print("3. Setting master password...")
            master_pwd_input = page.locator("input[name='master_pwd'], .generated_master_pwd_input")
            if master_pwd_input.count() > 0:
                master_pwd_input.first.fill(MASTER_PASSWORD)
            time.sleep(0.5)

            # Fill database name
            print(f"4. Setting database name: {DB_NAME}")
            page.fill("input#dbname, input[name='name']", DB_NAME)
            time.sleep(0.5)

            # Fill email
            print(f"5. Setting admin email: {ADMIN_EMAIL}")
            page.fill("input#login, input[name='login']", ADMIN_EMAIL)
            time.sleep(0.5)

            # Fill password
            print("6. Setting admin password...")
            page.fill("input#password, input[name='password']", ADMIN_PASSWORD)
            time.sleep(0.5)

            # Fill phone (optional field - skip or put default)
            print("7. Skipping phone number (optional)...")

            # Select language
            print("8. Setting language to English...")
            lang_select = page.locator("select[name='lang']")
            if lang_select.count() > 0:
                try:
                    # Try common values for English
                    for lang_val in ["en_US", "en-US", "en", "English (US)"]:
                        try:
                            page.select_option("select[name='lang']", lang_val, timeout=2000)
                            print(f"   Selected: {lang_val}")
                            break
                        except:
                            continue
                except:
                    print("   Language selection failed, continuing...")

            # Skip country selection (optional)
            print("9. Skipping country (optional)...")

            # Skip demo data (optional checkbox)
            print("10. Skipping demo data...")

            time.sleep(1)
            page.screenshot(path="Logs/odoo_before_create.png")

            # Submit the form
            print("\n" + "="*60)
            print("11. Creating database...")
            print("    This will take 2-3 minutes...")
            print("="*60)

            submit_time = time.time()

            # Find and click the submit button
            submit_btn = page.locator("button[type='submit']").or_(
                page.locator(".modal-footer .btn-primary")
            ).or_(
                page.locator("button:has-text('Create')")
            )

            submit_btn.first.click()

            # Wait for redirect to login page (database creation complete)
            print("Waiting for database creation...")
            try:
                page.wait_for_url("**/web/login", timeout=180000)
                elapsed = time.time() - submit_time
                print(f"\nDatabase created in {elapsed:.1f} seconds!")
                page.screenshot(path="Logs/odoo_created.png")
            except PlaywrightTimeoutError:
                elapsed = time.time() - submit_time
                print(f"Database creation still in progress after {elapsed:.1f} seconds")
                print(f"Current URL: {page.url}")
                page.screenshot(path="Logs/odoo_create_timeout.png")
                # Try to continue anyway
                if "login" in page.url.lower():
                    print("But we've been redirected to login page, continuing...")
                else:
                    raise

            time.sleep(3)

            # Login
            print("\n" + "="*60)
            print("12. Logging in...")
            print("="*60)

            # Wait for login form
            page.wait_for_selector("input[name='login'], input#login", timeout=10000)

            page.fill("input[name='login'], input#login", ADMIN_EMAIL)
            page.fill("input[name='password'], input#password", ADMIN_PASSWORD)

            page.screenshot(path="Logs/odoo_login_filled.png")

            print("Submitting login...")
            page.click("button[type='submit'], button:has-text('Log in')")

            # Wait for dashboard
            print("Waiting for dashboard...")
            page.wait_for_url("**/web**", timeout=60000)
            time.sleep(3)

            print("Login successful!")
            page.screenshot(path="Logs/odoo_dashboard.png")

            # Generate API key
            print("\n" + "="*60)
            print("13. Generating API Key...")
            print("="*60)

            # Click on user menu (top right)
            print("Opening user menu...")
            user_menu = page.locator(".o_user_menu, [data-menu-username], .oe_topbar_name").first
            user_menu.click()
            time.sleep(1)

            # Try multiple methods to get to API keys
            api_key_generated = False

            # Method 1: Click Preferences then look for API Keys
            try:
                print("Opening Preferences...")
                prefs_link = page.get_by_text("Preferences")
                if prefs_link.count() > 0:
                    prefs_link.click()
                    time.sleep(2)
                else:
                    page.goto(f"{ODOO_URL}/web#action=base.act_res_users_my", timeout=30000)
                    time.sleep(2)

                page.screenshot(path="Logs/odoo_preferences.png")

                # Look for "Account Security" or "API Keys" section
                security_found = False

                # Try clicking on Account Security if visible
                security_link = page.locator("a:has-text('Account Security'), button:has-text('Account Security')")
                if security_link.count() > 0:
                    print("Opening Account Security...")
                    security_link.first.click()
                    time.sleep(2)
                    security_found = True

                page.screenshot(path="Logs/odoo_account_security.png")

                # Look for API Keys section
                api_section = page.locator("*:has-text('API Keys'), *:has-text('Api Keys')")
                if api_section.count() > 0:
                    print("Found API Keys section")

                # Look for "New API Key" button
                new_key_btn = page.locator("button:has-text('New API Key'), a:has-text('New API Key'), button:has-text('Generate')")

                if new_key_btn.count() > 0:
                    print("Clicking 'New API Key' button...")
                    new_key_btn.first.click()
                    time.sleep(2)

                    page.screenshot(path="Logs/odoo_new_key_form.png")

                    # Fill in key name if there's an input
                    name_input = page.locator("input[type='text']").first
                    if name_input.count() > 0:
                        print(f"Setting API key name: {API_KEY_NAME}")
                        name_input.fill(API_KEY_NAME)
                        time.sleep(0.5)

                    # Save/Generate
                    save_btn = page.locator("button:has-text('Save'), button:has-text('Create'), button:has-text('Generate'), button[type='submit']").first
                    print("Generating API key...")
                    save_btn.click()
                    time.sleep(3)

                    page.screenshot(path="Logs/odoo_key_created.png")

                    # Try to extract the API key
                    print("Looking for generated API key...")

                    # Check various locations where key might be displayed
                    key_locators = [
                        "code",
                        ".api-key",
                        "[data-api-key]",
                        "input[readonly]",
                        ".alert strong",
                        ".modal-body code",
                        ".modal-body p:has-text('eyJ')",
                    ]

                    for locator in key_locators:
                        elements = page.locator(locator).all()
                        for elem in elements:
                            try:
                                text = elem.text_content() or ""
                                val = elem.input_value() if elem.get_attribute("type") == "text" or elem.get_attribute("readonly") else ""

                                # API keys are JWT-like strings starting with eyJ
                                combined = text + " " + val
                                if "eyJ" in combined and len(combined) > 50:
                                    # Extract the JWT token
                                    import re
                                    match = re.search(r'eyJ[\\w\\-\\.]+', combined)
                                    if match:
                                        api_key = match.group(0)
                                        print(f"\n" + "="*60)
                                        print(f"API KEY FOUND: {api_key}")
                                        print("="*60)

                                        # Save to file
                                        with open("Logs/odoo_api_key.txt", "w") as f:
                                            f.write(f"ODOO_URL={ODOO_URL}\n")
                                            f.write(f"ODOO_DB={DB_NAME}\n")
                                            f.write(f"ODOO_API_KEY={api_key}\n")
                                            f.write(f"ODOO_ADMIN_EMAIL={ADMIN_EMAIL}\n")
                                            f.write(f"ODOO_ADMIN_PASSWORD={ADMIN_PASSWORD}\n")
                                            f.write(f"ODOO_MASTER_PASSWORD={MASTER_PASSWORD}\n")

                                        print("\nAPI key saved to: Logs/odoo_api_key.txt")
                                        api_key_generated = True
                                        break
                            except:
                                pass

                        if api_key_generated:
                            break

                    if not api_key_generated:
                        print("\nCould not extract API key from page.")
                        print("Please check screenshot: Logs/odoo_key_created.png")
                        print("And manually save the API key to Logs/odoo_api_key.txt")

                else:
                    print("Could not find 'New API Key' button")

            except Exception as e:
                print(f"Error during API key generation: {e}")
                import traceback
                traceback.print_exc()
                page.screenshot(path="Logs/odoo_api_error.png")

            print("\n" + "="*60)
            print("Setup Complete!")
            print("="*60)
            print("\nKeeping browser open for 30 seconds for verification...")
            time.sleep(30)

            return api_key_generated

        except Exception as e:
            print(f"\nError during setup: {e}")
            import traceback
            traceback.print_exc()
            page.screenshot(path="Logs/odoo_fatal_error.png")
            return None

        finally:
            browser.close()


if __name__ == "__main__":
    result = complete_setup()
    sys.exit(0 if result else 1)
