#!/usr/bin/env python3
"""
Complete Odoo 19 setup and API key generation using Playwright.
"""

import time
import sys
import re
from playwright.sync_api import sync_playwright, TimeoutError as PlaywrightTimeoutError

# Configuration
ODOO_URL = "http://localhost:8069"
ADMIN_EMAIL = "admin@example.com"
ADMIN_PASSWORD = "Admin@123456"
DB_NAME = "odoo_production"
MASTER_PASSWORD = "zmiy-853z-yg9k"  # Auto-generated by Odoo
API_KEY_NAME = "AI Employee Integration"


def complete_setup():
    """Complete Odoo setup and generate API key."""

    with sync_playwright() as p:
        browser = p.chromium.launch(headless=False, slow_mo=300)
        context = browser.new_context()
        page = context.new_page()

        try:
            print("="*60)
            print("Odoo 19 Setup - Starting")
            print("="*60)

            # Navigate to database manager
            print(f"\n1. Opening database manager...")
            page.goto(f"{ODOO_URL}/web/database/manager", wait_until="networkidle", timeout=30000)
            time.sleep(2)
            page.screenshot(path="Logs/odoo_step1_manager.png")

            # Click "Create Database" button
            print("2. Clicking 'Create Database' button...")
            page.click("button[data-bs-target='.o_database_create']")
            time.sleep(1)

            # Fill master password
            print("3. Setting master password...")
            page.fill("input[name='master_pwd']", MASTER_PASSWORD)
            time.sleep(0.5)

            # Fill database name
            print(f"4. Setting database name: {DB_NAME}")
            page.fill("input#dbname", DB_NAME)
            time.sleep(0.5)

            # Fill email
            print(f"5. Setting admin email: {ADMIN_EMAIL}")
            page.fill("input#login", ADMIN_EMAIL)
            time.sleep(0.5)

            # Fill password
            print("6. Setting admin password...")
            page.fill("input[name='password'], input#password", ADMIN_PASSWORD)
            time.sleep(0.5)

            # Select language
            print("7. Setting language to English...")
            if page.locator("select[name='lang']").count() > 0:
                page.select_option("select[name='lang']", "en_US")

            # Select country - skip for now as it's optional and may have dynamic loading
            print("8. Skipping country selection (optional field)...")

            page.screenshot(path="Logs/odoo_step9_before_create.png")

            # Submit the form
            print("\n" + "="*60)
            print("9. Creating database...")
            print("   This will take 2-3 minutes...")
            print("="*60)

            submit_time = time.time()
            page.click("button[type='submit']")

            # Wait for redirect to login page (database creation complete)
            try:
                page.wait_for_url("**/web/login", timeout=180000)
                elapsed = time.time() - submit_time
                print(f"\nDatabase created in {elapsed:.1f} seconds!")
                page.screenshot(path="Logs/odoo_step10_created.png")
            except PlaywrightTimeoutError:
                print("Database creation timed out. Checking current state...")
                page.screenshot(path="Logs/odoo_step10_timeout.png")
                print(f"Current URL: {page.url}")

            time.sleep(3)

            # Login
            print("\n" + "="*60)
            print("10. Logging in...")
            print("="*60)

            page.fill("input[name='login'], input#login", ADMIN_EMAIL)
            page.fill("input[name='password'], input#password", ADMIN_PASSWORD)
            page.screenshot(path="Logs/odoo_step11_login_filled.png")

            print("Submitting login...")
            page.click("button[type='submit'], button:has-text('Log in')")

            # Wait for dashboard
            page.wait_for_url("**/web**", timeout=60000)
            time.sleep(3)

            print("Login successful!")
            page.screenshot(path="Logs/odoo_step12_dashboard.png")

            # Generate API key
            print("\n" + "="*60)
            print("11. Generating API Key...")
            print("="*60)

            # Click on user menu (top right)
            print("Opening user menu...")
            user_menu = page.locator(".o_user_menu, [data-menu-username]").first
            user_menu.click()
            time.sleep(1)

            # Click on "Preferences"
            print("Opening Preferences...")
            page.get_by_text("Preferences").click()
            time.sleep(2)

            page.screenshot(path="Logs/odoo_step13_preferences.png")

            # Look for Account Security tab/section
            account_security_found = False

            # Try different selectors for Account Security
            selectors = [
                "a:has-text('Account Security')",
                "button:has-text('Account Security')",
                "[data-menu-key='account_security']",
                ".o_setting_center .nav-item:has-text('Account Security')",
            ]

            for selector in selectors:
                if page.locator(selector).count() > 0:
                    print(f"Found Account Security with: {selector}")
                    page.locator(selector).first.click()
                    account_security_found = True
                    time.sleep(2)
                    break

            if not account_security_found:
                print("Account Security not found, trying direct URL...")
                page.goto(f"{ODOO_URL}/web#action=base.act_res_users_my", timeout=30000)
                time.sleep(2)

            page.screenshot(path="Logs/odoo_step14_account_security.png")

            # Look for API Keys section
            api_section_found = False

            # Try to find "API Keys" text or section
            if page.get_by_text("API Keys").count() > 0:
                print("Found API Keys section")
                api_section_found = True

            # Look for "New API Key" button
            new_key_selectors = [
                "button:has-text('New API Key')",
                "button:has-text('Generate')",
                "a:has-text('New API Key')",
                ".btn-primary:has-text('New')",
            ]

            button_clicked = False
            for selector in new_key_selectors:
                try:
                    if page.locator(selector).count() > 0:
                        print(f"Clicking button: {selector}")
                        page.locator(selector).first.click()
                        button_clicked = True
                        time.sleep(2)
                        break
                except:
                    pass

            if not button_clicked:
                print("Could not find 'New API Key' button")
                print("Looking for any button containing 'New' or 'Generate'...")
                buttons = page.locator("button").all()
                print(f"Found {len(buttons)} buttons on page")
                for i, btn in enumerate(buttons[:20]):
                    text = btn.text_content() or ""
                    if text:
                        print(f"  Button {i}: {text[:50]}")

            page.screenshot(path="Logs/odoo_step15_new_key.png")

            # Fill in API key name if there's an input field
            name_selectors = [
                "input[name='name']",
                "input[placeholder*='name']",
                "input#name",
                "input[type='text']",
            ]

            for selector in name_selectors:
                try:
                    if page.locator(selector).count() > 0:
                        print(f"Filling API key name with: {selector}")
                        page.locator(selector).first.fill(API_KEY_NAME)
                        time.sleep(0.5)
                        break
                except:
                    pass

            # Submit/Save
            save_selectors = [
                "button[type='submit']",
                "button:has-text('Save')",
                "button:has-text('Create')",
                "button:has-text('Generate')",
                "button:has-text('Confirm')",
            ]

            saved = False
            for selector in save_selectors:
                try:
                    if page.locator(selector).count() > 0:
                        print(f"Clicking save button: {selector}")
                        page.locator(selector).first.click()
                        saved = True
                        time.sleep(3)
                        break
                except:
                    pass

            if saved:
                page.screenshot(path="Logs/odoo_step16_key_created.png")

                # Try to find the generated key
                print("\nLooking for generated API key...")

                # Check for code elements, readonly inputs, or alert boxes
                key_selectors = [
                    "code",
                    ".api-key",
                    "[data-api-key]",
                    "input[readonly]",
                    ".alert",
                    ".modal-body code",
                ]

                api_key = None
                for selector in key_selectors:
                    try:
                        elements = page.locator(selector).all()
                        for elem in elements:
                            text = elem.text_content() or ""
                            # API keys are typically long alphanumeric strings
                            if re.match(r'^[a-zA-Z0-9_-]{20,}$', text.strip()):
                                api_key = text.strip()
                                print(f"Found API key with selector {selector}: {api_key}")
                                break
                        if api_key:
                            break
                    except:
                        pass

                if not api_key:
                    # Try to get from input values
                    try:
                        readonly_inputs = page.locator("input[readonly]").all()
                        for inp in readonly_inputs:
                            val = inp.input_value() or ""
                            if re.match(r'^[a-zA-Z0-9_-]{20,}$', val):
                                api_key = val
                                print(f"Found API key from input: {api_key}")
                                break
                    except:
                        pass

                if api_key:
                    print("\n" + "="*60)
                    print(f"API KEY GENERATED: {api_key}")
                    print("="*60)

                    # Save to file
                    with open("Logs/odoo_api_key.txt", "w") as f:
                        f.write(f"ODOO_URL={ODOO_URL}\n")
                        f.write(f"ODOO_DB={DB_NAME}\n")
                        f.write(f"ODOO_API_KEY={api_key}\n")
                        f.write(f"ODOO_ADMIN_EMAIL={ADMIN_EMAIL}\n")
                        f.write(f"ODOO_ADMIN_PASSWORD={ADMIN_PASSWORD}\n")
                        f.write(f"ODOO_MASTER_PASSWORD={MASTER_PASSWORD}\n")

                    print("\nAPI key saved to: Logs/odoo_api_key.txt")
                    return api_key
                else:
                    print("\nCould not extract API key from page.")
                    print("Please check the screenshot: Logs/odoo_step16_key_created.png")
                    print("And manually copy the API key to Logs/odoo_api_key.txt")
            else:
                print("\nCould not complete API key generation automatically.")
                print("Please complete it manually in the browser.")
                page.screenshot(path="Logs/odoo_step_final_manual.png")

            print("\n" + "="*60)
            print("Setup Complete - Browser will remain open for 10 seconds")
            print("="*60)
            time.sleep(10)

            return None

        except Exception as e:
            print(f"\nError during setup: {e}")
            import traceback
            traceback.print_exc()
            page.screenshot(path="Logs/odoo_error.png")
            return None

        finally:
            browser.close()


if __name__ == "__main__":
    result = complete_setup()
    sys.exit(0 if result else 1)
