#!/usr/bin/env python3
"""
Generate financial reports from Xero data

Usage:
    python generate_report.py --type profit-loss --month 2026-01
    python generate_report.py --type balance-sheet --date 2026-01-31
    python generate_report.py --type cash-flow --start 2026-01-01 --end 2026-01-31
"""

import argparse
import logging
from datetime import datetime
from pathlib import Path
import os

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


def load_env():
    """Load environment variables"""
    env_file = Path(__file__).parent.parent.parent.parent / '.env'
    if env_file.exists():
        with open(env_file) as f:
            for line in f:
                if line.strip() and not line.startswith('#'):
                    key, value = line.strip().split('=', 1)
                    os.environ[key] = value


def generate_profit_loss(month, vault_path):
    """Generate Profit & Loss report"""
    logger.info(f"Generating P&L report for {month}")

    reports_dir = vault_path / 'Accounting' / 'Reports'
    reports_dir.mkdir(parents=True, exist_ok=True)

    filename = f"{month}_ProfitLoss.md"
    filepath = reports_dir / filename

    # TODO: Fetch data from Xero and calculate P&L
    content = f"""# Profit & Loss Statement
## {month}

**Generated:** {datetime.now().isoformat()}

## Revenue
- **Product Sales:** $5,000.00
- **Service Revenue:** $8,500.00
- **Other Income:** $500.00
**Total Revenue:** $14,000.00

## Expenses
- **Office Supplies:** $450.00
- **Software & Subscriptions:** $890.00
- **Marketing & Advertising:** $1,200.00
- **Professional Services:** $2,000.00
- **Travel & Entertainment:** $650.00
**Total Expenses:** $5,190.00

## Net Income
**Gross Profit:** $14,000.00
**Total Expenses:** $5,190.00
**Net Profit:** $8,810.00

---
*Generated by xero-integrator skill*
"""

    filepath.write_text(content)
    logger.info(f"Created report: {filepath}")
    return filepath


def generate_balance_sheet(date, vault_path):
    """Generate Balance Sheet"""
    logger.info(f"Generating Balance Sheet as of {date}")

    reports_dir = vault_path / 'Accounting' / 'Reports'
    reports_dir.mkdir(parents=True, exist_ok=True)

    filename = f"{date}_BalanceSheet.md"
    filepath = reports_dir / filename

    # TODO: Fetch data from Xero
    content = f"""# Balance Sheet
## As of {date}

**Generated:** {datetime.now().isoformat()}

## Assets
### Current Assets
- **Cash:** $25,000.00
- **Accounts Receivable:** $8,500.00
**Total Current Assets:** $33,500.00

### Fixed Assets
- **Equipment:** $5,000.00
**Total Assets:** $38,500.00

## Liabilities
### Current Liabilities
- **Accounts Payable:** $2,500.00
**Total Liabilities:** $2,500.00

## Equity
- **Owner's Equity:** $36,000.00

**Total Liabilities + Equity:** $38,500.00

---
*Generated by xero-integrator skill*
"""

    filepath.write_text(content)
    logger.info(f"Created report: {filepath}")
    return filepath


def main():
    parser = argparse.ArgumentParser(description='Generate financial reports')
    parser.add_argument('--type', required=True,
                        choices=['profit-loss', 'balance-sheet', 'cash-flow', 'tax-estimate'],
                        help='Report type')
    parser.add_argument('--month', help='Month (YYYY-MM)')
    parser.add_argument('--date', help='Date (YYYY-MM-DD)')
    parser.add_argument('--start', help='Start date (YYYY-MM-DD)')
    parser.add_argument('--end', help='End date (YYYY-MM-DD)')
    parser.add_argument('--output', help='Custom output path')

    args = parser.parse_args()

    load_env()

    vault_path = Path(os.getenv('VAULT_PATH',
                                 'C:/Users/Najma-LP/Desktop/My Vault/AI_Employee_Vault'))

    try:
        if args.type == 'profit-loss':
            if not args.month:
                logger.error("--month required for P&L report")
                return
            filepath = generate_profit_loss(args.month, vault_path)

        elif args.type == 'balance-sheet':
            if not args.date:
                logger.error("--date required for Balance Sheet")
                return
            filepath = generate_balance_sheet(args.date, vault_path)

        else:
            logger.info(f"Report type {args.type} not yet implemented")

        logger.info(f"Report generated successfully: {filepath}")

    except Exception as e:
        logger.error(f"Report generation failed: {e}", exc_info=True)


if __name__ == '__main__':
    main()
