#!/usr/bin/env python3
"""
Quick test script to generate a sample Xero event file
Demonstrates the Xero watcher file format
"""

from pathlib import Path
from datetime import datetime
import uuid

# Vault path
vault_path = Path(__file__).parent.parent / 'AI_Employee_Vault'
needs_action = vault_path / 'Needs_Action'
needs_action.mkdir(parents=True, exist_ok=True)

# Generate timestamp
timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')

# Create sample invoice file
invoice_content = f"""---
type: xero_event
event_type: new_invoice
source: xero_watcher_test
created: {datetime.now().isoformat()}
status: pending
priority: high
invoice_id: {uuid.uuid4()}
---

# New Invoice Created - INV-TEST-{timestamp}

## Invoice Details
- **Customer:** Acme Corp - Test Customer
- **Amount:** $2,500.00
- **Due Date:** 2026-02-14
- **Status:** AUTHORISED
- **Date:** 2026-01-14

## Action Required
A new invoice has been created and awaiting payment.

**Suggested Actions:**
1. Verify invoice details are correct
2. Send invoice to customer via email-sender skill
3. Add to accounts receivable tracking
4. Set up payment reminder for due date
5. Update cash flow projections

**Next Steps:**
- [ ] Verify invoice accuracy
- [ ] Confirm customer contact information (acme@example.com)
- [ ] Schedule payment follow-up
- [ ] Update financial dashboard
- [ ] Add to weekly CEO briefing

---

**Xero Event ID:** invoice_{uuid.uuid4()}
**Detected:** {datetime.now().isoformat()}
**Test File:** Generated by test_xero_sample.py
"""

invoice_file = needs_action / f'xero_new_invoice_TEST_{timestamp}.md'
invoice_file.write_text(invoice_content)
print(f"[OK] Created: {invoice_file.name}")

# Create sample overdue invoice file
overdue_content = f"""---
type: xero_event
event_type: overdue_invoice
source: xero_watcher_test
created: {datetime.now().isoformat()}
status: pending
priority: urgent
invoice_id: {uuid.uuid4()}
---

# Overdue Invoice - INV-OVERDUE-{timestamp}

## Invoice Details
- **Customer:** Beta Industries
- **Amount:** $3,750.00
- **Due Date:** 2026-01-07 (7 days overdue)
- **Status:** AUTHORISED
- **Original Date:** 2025-12-24

## Action Required
This invoice is now 7 days overdue and requires follow-up.

**Suggested Actions:**
1. Send polite payment reminder email
2. Call customer to check on payment status
3. Offer payment plan if needed
4. Check if there are delivery or quality issues
5. Update late payment tracking

**Next Steps:**
- [ ] Send first overdue reminder email
- [ ] Schedule follow-up call
- [ ] Check customer payment history
- [ ] Review account notes
- [ ] Escalate if no response in 3 days

---

**Xero Event ID:** invoice_{uuid.uuid4()}
**Detected:** {datetime.now().isoformat()}
**Days Overdue:** 7
**Test File:** Generated by test_xero_sample.py
"""

overdue_file = needs_action / f'xero_overdue_invoice_TEST_{timestamp}.md'
overdue_file.write_text(overdue_content)
print(f"[OK] Created: {overdue_file.name}")

# Create sample bill file
bill_content = f"""---
type: xero_event
event_type: new_bill
source: xero_watcher_test
created: {datetime.now().isoformat()}
status: pending
priority: high
bill_id: {uuid.uuid4()}
---

# New Bill Received - BILL-{timestamp}

## Bill Details
- **Vendor:** Cloud Services Inc.
- **Amount:** $450.00
- **Due Date:** 2026-01-31
- **Status:** RECEIVED
- **Date:** 2026-01-14
- **Reference:** Monthly cloud hosting

## Action Required
A new vendor bill has been received and needs processing.

**Suggested Actions:**
1. Verify bill details are correct
2. Check against purchase order if applicable
3. Approve for payment
4. Schedule payment before due date
5. Categorize expense properly

**Next Steps:**
- [ ] Verify against contract/PO
- [ ] Review line items for accuracy
- [ ] Approve for payment
- [ ] Schedule payment (due in 17 days)
- [ ] Update expense tracking
- [ ] Add to monthly report

---

**Xero Event ID:** bill_{uuid.uuid4()}
**Detected:** {datetime.now().isoformat()}
**Test File:** Generated by test_xero_sample.py
"""

bill_file = needs_action / f'xero_new_bill_TEST_{timestamp}.md'
bill_file.write_text(bill_content)
print(f"[OK] Created: {bill_file.name}")

print(f"\n[OK] Successfully created 3 Xero test event files in:")
print(f"   {needs_action}")
print(f"\nThese files demonstrate:")
print(f"  - New Invoice (ready to send)")
print(f"  - Overdue Invoice (requires follow-up)")
print(f"  - New Bill (needs approval)")
